export const COUNTIES: { name: string; constituencies: string[] }[] = [
  {
    name: "Nairobi County",

    constituencies: [
      "Westlands Constituency",
      "Dagoretti North Constituency",
      "Langata constituency",
      "Kibra constituency",
      "Dagoretti north constituency",
      "Dagoretti south constituency",
      "Westlands constituency",
      "Starehe constituency",
      "Mathare constituency",
      "Roysambu constituency",
      "Ruaraka constituency",
      "Makadara constituency",
      "Embakasi central constituency",
      "Embakasi north constituency",
      "Embakasi east constituency",
      "Embakasi west constituency",
      "Embakasi south constituency",
      "Kamukunji constituency",
      "Kasarani constituency",
    ],
  },
  {
    name: "Mombasa county",
    constituencies: [
      "Likoni constituency",
      "Nyali constituency",
      "Kisauni constituency",
      "Changamwe constituency",
      "Jomvu constituency",
      "Mvita constituency",
    ],
  },
  {
    name: "Kwale county",
    constituencies: [
      "Matuga constituency",
      "Kinango constituency",
      "LungaLunga constituency",
      "Msambweni constituency",
    ],
  },
  {
    name: "Kilifi county ",
    constituencies: [
      "Ganze constituency",
      "Rabai constituency",
      "Malindi constituency",
      "Kaloleni constituency",
      "Magarini constituency",
      "Kilifi north constituency",
      "Kilifi south constituency",
    ],
  },
  {
    name: "Tana River county",
    constituencies: [
      "Galole constituency",
      "Garsen constituency",
      "Bura constituency",
    ],
  },
  {
    name: "Lamu county",
    constituencies: ["Lamu East constituency ", "Lamu West constituency "],
  },
  {
    name: "Taita Taveta county",
    constituencies: [
      "Voi constituency",
      "Wundanyi constituency",
      "Taveta constituency",
      "Mwatate constituency",
    ],
  },
  {
    name: "Garissa county",
    constituencies: [
      "Garissa township constituency (Formerly Dujis)",
      "Lagdera constituency",
      "Fafi constituency",
      "Dadaab constituency",
      "Ijara constituency",
      "Balambala constituency",
    ],
  },
  {
    name: "Wajir county",
    constituencies: [
      "Wajir East constituency",
      "Wajir North constituency",
      "Wajir South constituency",
      "Wajir West constituency",
      "Eldas constituency",
      "Tarbaj constituency",
    ],
  },
  {
    name: "Mandera county ",
    constituencies: [
      "Mandera East constituency",
      "Lafey constituency",
      "Mandera West constituency",
      "Mandera Central constituency",
      "Mandera North constituency",
      "Banisa constituency",
    ],
  },
  {
    name: "Marsabit county",
    constituencies: [
      "Saku constituency",
      "Laisamis constituency",
      "Moyale constituency",
      "North Horr constituency",
    ],
  },
  {
    name: "Isiolo county",
    constituencies: ["Isiolo South constituency", "Isiolo North constituency"],
  },
  {
    name: "Meru county",
    constituencies: [
      "Imenti North constituency",
      "Buuri constituency",
      "Imenti central constituency",
      "Imenti south constituency",
      "Igembe north constituency",
      "Igembe central constituency",
      "Igembe South constituency",
      "Tigania east constituency",
      "Tigania West constituency",
    ],
  },
  {
    name: "Tharaka Nithi county",
    constituencies: [
      "Maara constituency",
      "Chuka constituency",
      "Tharaka constituency",
    ],
  },
  {
    name: " Embu county",
    constituencies: [
      "Manyatta constituency",
      "Runyenjes constituency",
      "Mbeere North constituency",
      "Mbeere south constituency",
    ],
  },
  {
    name: "Kitui County",
    constituencies: [
      "Kitui Central constituency",
      "Kitui West constituency",
      "Kitui east constituency",
      "Kitui south constituency",
      "Mwingi west constituency",
      "Mwingi east constituency",
      "Mwingi central constituency",
      "Mwingi north constituency",
      "Kitui rural constituency",
    ],
  },
  {
    name: "Makueni County",
    constituencies: [
      "Kibwezi east constituency",
      "Kibwezi west constituency",
      "Mbooni constituency",
      "Kaiti constituency",
      "Kilome constituency",
      "Makueni constituency",
    ],
  },
  {
    name: "Nyandarua County",
    constituencies: [
      "Ol Kalou constituency",
      "Ol Joro Orok constituency",
      "Nyandarua south constituency",
      "Kinangop constituency",
      "Kipipiri constituency",
      "Ndaragua constituency",
    ],
  },
  {
    name: "Nyeri County",
    constituencies: [
      "Kieni constituency",
      "Nyeri town constituency",
      "Othaya constituency",
      "Mukurweini constituency",
      "Mathira constituency",
      "Tetu constituency",
    ],
  },
  {
    name: "Kirinyaga County",
    constituencies: [
      "Ndia constituency",
      "Kirinyaga central constituency",
      "Mwea constituency",
      " Gichugu constituency",
    ],
  },
  {
    name: "Murang'a County",
    constituencies: [
      "Kiharu constituency",
      "Kigumo constituency",
      "Kandara constituency",
      "Kangema constituency",
      "Mathioya constituency",
      "Gatanga constituency",
      "Maragwa constituency",
    ],
  },
  {
    name: "Kiambu County",
    constituencies: [
      "Githunguri constituency",
      "Ruiru constituency",
      "Juja constituency",
      "Limuru constituency",
      "Lari constituency",
      "Kiambaa constituency",
      "Kiambu constituency",
      "Kikuyu constituency",
      "Kabete constituency",
      "Gatundu South constituency",
      "Gatundu North constituency",
      "Thika town constituency",
    ],
  },
  {
    name: "Turkana County",
    constituencies: [
      "Turkana central constituency",
      "Turkana west constituency",
      "Turkana south constituency",
      "Turkana east constituency",
      "Turkana north constituency",
      "Loima constituency",
    ],
  },
  {
    name: "West Pokot County",
    constituencies: [
      "Sigor constituency",
      "Kacheliba constituency",
      "Pokot South constituency",
      "Kapenguria constituency",
    ],
  },
  {
    name: "Samburu County",
    constituencies: [
      "Samburu west constituency",
      "Samburu East constituency",
      "Samburu North constituency",
    ],
  },
  {
    name: "Trans Zoia County",
    constituencies: [
      "Saboti constituency",
      "Kiminini constituency",
      "Kwanza constituency",
      "Endebess constituency",
      "Cherangani constituency",
    ],
  },
  {
    name: " Uasin Gishu County",
    constituencies: [
      "Turbo constituency",
      "Soy constituency",
      "Ainabkoi constituency",
      "Moiben constituency",
      "Kesses constituency",
      "Kapseret constituency",
    ],
  },
  {
    name: "Elgeyo Marakwet",
    constituencies: [
      " Keiro North constituency",
      " Keiyo South constituency",
      "Marakwet West constituency",
      "Marakwet East constituency",
    ],
  },
  {
    name: "Nandi County",
    constituencies: [
      "Chesumei constituency",
      "Emgwen constituency",
      "Tinderet constituency",
      "Nandi hills constituency",
      "Aldai constituency",
      "Mosop constituency",
    ],
  },
  {
    name: "Baringo County",
    constituencies: [
      "Baringo south constituency",
      "Baringo central constituency",
      "Tiaty constituency",
      "Baringo north constituency",
      "Eldama Ravine constituency",
      "Mogotio constituency",
    ],
  },
  {
    name: "Laikipia County",
    constituencies: [
      "Laikipia North constituency",
      "Laikipia West constituency",
      "Laikipia East constituency",
    ],
  },
  {
    name: "Nakuru County",
    constituencies: [
      "Naivasha constituency",
      "Gilgil constituency",
      "Kuresoi south constituency",
      "Kuresoi North constituency",
      "Molo constituency",
      "Subukia constituency",
      "Bahati constituency",
      "Njoro constituency",
      "Nakuru East constituency",
      "Nakuru west constituency",
      "Rongai constituency",
    ],
  },
  {
    name: "Narok County",
    constituencies: [
      "Narok North constituency",
      "Narok East constituency",
      "Narok south constituency",
      " Narok west constituency",
      "Kilgoris constituency",
      "Emurua Dikirr",
    ],
  },
  {
    name: "Kajiado County",
    constituencies: [
      "Kajiado Central constituency",
      "Kajiado east constituency",
      "Kajiado North constituency",
      "Kajiado west constituency",
      "Kajiado south constituency",
    ],
  },
  {
    name: "Kericho County",
    constituencies: [
      "Ainamoi constituency",
      "Soin Sigowet constituency",
      "Kipkelion west constituency",
      "Belgut constituency",
      "Buret constituency",
      "Kipkelion east constituency",
    ],
  },
  {
    name: "Bomet County",
    constituencies: [
      "Bomet central constituency",
      "Bomet East constituency",
      "Konoin constituency",
      "Chepalungu constituency",
      "Sotik constituency",
    ],
  },
  {
    name: "Kakamega County",
    constituencies: [
      "Khwisero constituency",
      "Kakamega south constituency",
      "Lurambi constituency",
      "Shinyalu constituency",
      "Butere constituency",
      "Mumias west constituency",
      "Mumias east constituency",
      "Malava constituency",
      "Lugari constituency",
      "Likuyani constituency",
      "Matungu constituency",
      "Navakholo constituency",
    ],
  },
  {
    name: "Vihiga County",
    constituencies: [
      "Emuhaya constituency",
      "Luanda constituency",
      "Vihiga constituency",
      "Sabatia constituency",
      "Hamisi constituency",
    ],
  },
  {
    name: "Bungoma County",
    constituencies: [
      "Kanduyi constituency",
      "Bumula constituency",
      "Kimilili constituency",
      "Sirisia constituency",
      "Tongeren constituency",
      "Kabuchhai constituency",
      "Mt Elgon constituency",
      "Webuye east constituency",
      "Webuye west constituency",
    ],
  },
  {
    name: "Busia County",
    constituencies: [
      "Busia constituency",
      "Nambale constituency",
      "Bundalangi constituency",
      "Funyula constituency",
      "Teso north constituency",
      "Teso south constituency",
      "Butula constituency",
    ],
  },
  {
    name: "Siaya County",
    constituencies: [
      "Gem constituency",
      "Alego Usonga constituency",
      "Bondo constituency",
      "Rarieda constituency",
      "Ugenya constituency",
      "Ugunja constituency",
    ],
  },
  {
    name: "Kisumu County",
    constituencies: [
      "Kisumu west constituency",
      "Seme constituency",
      "Kisumu east constituency",
      "Kisumu central constituency",
      "Nyando constituency",
      "Nyakach constituency",
      "Muhoroni constituency",
      "Ruiru constituency",
    ],
  },
  {
    name: "Homabay County",
    constituencies: [
      "Homa bay constituency",
      "Rangwe constituency",
      "Ndhiwa constituency",
      "Suba constituency",
      "Mbita constituency",
      "Kasipul kabondo constituency",
      "Kasipul constituency",
      "Rachuonyo constituency",
    ],
  },
  {
    name: "Migori",
    constituencies: [
      "Rongo constituency",
      "Uriri constituency",
      "Kuria West constituency",
      "Kuria East constituency",
      "Suna East constituency",
      "Suna West constituency",
      "Nyatike constituency",
      "Awendo constituency",
    ],
  },
  {
    name: "Kisii County",
    constituencies: [
      "Kitutu chache south constituency",
      "Nyaribari chache constituency",
      "Kitutu chache north constituency",
      "Nyaribari masaba constituency",
      "Bobasi constituency",
      "Bomachoge borabu constituency",
      "Bomachoge chache constituency",
      "Bonchari constituency",
      "South mugirango constituency",
      "Bobasi constituency",
    ],
  },
  {
    name: "Nyamira County",
    constituencies: [
      "West mugirango constituency",
      "North mugirango constituency",
      "Borabu constituency",
      "Kitutu Masaba constituency",
    ],
  },
];

export const COUNTYNAMES = COUNTIES.map((county) => county.name);

export const CONTITUENCIES: string[] = COUNTIES.reduce(
  (acc: string[], county) => {
    return acc.concat(county.constituencies);
  },
  []
);
